'use client';

import { useEffect, useState } from 'react';
import { demoFetch as fetch } from '@/lib/demo-store';

type Analysis = { blocker: string; explanation: string; recommendedAction: string; recommendedState: string; responsibleRole: string; confidence: number; humanReviewRequired: true; communicationSummary?: string };
type Props = { refillId: string; currentState: string; onActionComplete: () => Promise<void> };

function confidenceLabel(value: number) { return value >= 0.8 ? 'High' : value >= 0.55 ? 'Medium' : 'Low'; }

export function AIWorkflowInsight({ refillId, currentState, onActionComplete }: Props) {
  const [analysis, setAnalysis] = useState<Analysis | null>(null); const [source, setSource] = useState<'gemini' | 'deterministic' | null>(null); const [notice, setNotice] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [reviewing, setReviewing] = useState(false); const [saving, setSaving] = useState(false);
  async function analyze() { setLoading(true); setError(''); try { const response = await fetch('/api/ai/analyze-refill', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ refillId }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error || 'Unable to analyze this refill.'); setAnalysis(body.analysis); setSource(body.source); setNotice(body.notice || ''); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to analyze this refill.'); } finally { setLoading(false); } }
  useEffect(() => { analyze(); }, [refillId]);
  async function confirmRecommendation() { if (!analysis || analysis.recommendedState === currentState) return; setSaving(true); try { const verifyingFulfillment = analysis.recommendedState === 'RESOLVED'; const response = await fetch(verifyingFulfillment ? `/api/refills/${refillId}/verify-fulfillment` : `/api/refills/${refillId}/transition`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(verifyingFulfillment ? { reason: `Human-approved operational recommendation: ${analysis.recommendedAction}` } : { targetState: analysis.recommendedState, reason: `Human-approved operational recommendation: ${analysis.recommendedAction}` }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error || 'Unable to apply this workflow action.'); setReviewing(false); await onActionComplete(); await analyze(); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to apply this workflow action.'); } finally { setSaving(false); } }
  return <section className="ai-panel"><div className="ai-heading"><div><span className="ai-kicker">OPERATIONAL WORKFLOW RECOMMENDATION</span><h2>AI Workflow Insight</h2></div><span className="ai-mark">✦</span></div>{loading ? <div className="ai-state">Analyzing workflow...</div> : error ? <div className="ai-state ai-error">Unable to analyze this refill. Workflow remains unchanged.<button className="ai-retry" onClick={analyze}>Try again</button></div> : analysis ? <><div className="ai-notice">{notice || (source === 'gemini' ? 'Gemini analysis validated against workflow rules.' : '')}</div><div className="ai-facts"><div><span>WHAT'S HAPPENING?</span><strong>{analysis.explanation}</strong></div><div><span>BLOCKER</span><strong>{analysis.blocker}</strong></div><div><span>RECOMMENDED NEXT ACTION</span><strong>{analysis.recommendedAction}</strong></div><div><span>WHO NEEDS TO ACT?</span><strong>{analysis.responsibleRole}</strong></div><div><span>CONFIDENCE</span><strong>{confidenceLabel(analysis.confidence)} <small>({Math.round(analysis.confidence * 100)}%)</small></strong></div><div><span>HUMAN REVIEW</span><strong>Required</strong></div></div>{analysis.communicationSummary && <p className="ai-summary"><span>COMMUNICATION SUMMARY</span>{analysis.communicationSummary}</p>}{analysis.confidence < 0.55 && <p className="ai-low-confidence">Low-confidence recommendation — human review required.</p>}<button className="ai-review" disabled={analysis.recommendedState === currentState} onClick={() => setReviewing(true)}>{analysis.recommendedState === currentState ? 'No workflow change suggested' : 'Review recommendation'} <span>→</span></button></> : null}<div className={`modal-backdrop ${reviewing ? 'open' : ''}`} role="presentation"><div className="phase-modal" role="dialog" aria-modal="true"><h2>Confirm operational action</h2><p>This recommendation will request a workflow transition. It will not make a clinical decision.</p><p>Action: <strong>{analysis?.recommendedAction}</strong><br />State: <strong>{currentState} → {analysis?.recommendedState}</strong></p><div className="modal-actions"><button className="secondary" onClick={() => setReviewing(false)}>Cancel</button><button className="confirm" disabled={saving} onClick={confirmRecommendation}>{saving ? 'Applying...' : 'Confirm action'}</button></div></div></div></section>;
}
