'use client';

import { useEffect, useState } from 'react';
import { demoFetch as fetch } from '@/lib/demo-store';

type Communication = { id: string; recipient: string; recipientRole: string; channel: string; message: string; integration: string; succeeded: boolean; errorMessage: string | null; attemptCount: number; createdAt: string; sender: { name: string } | null };
type User = { role: string };
type Props = { refillId: string; onComplete: () => Promise<void> };
const rolePermissions: Record<string, string[]> = { PHARMACY_STAFF: ['PHARMACY'], PRACTICE_STAFF: ['PROVIDER', 'PATIENT'], PROVIDER: [], ADMIN: ['PROVIDER', 'PHARMACY', 'PATIENT'] };

export function CommunicationCenter({ refillId, onComplete }: Props) {
  const [communications, setCommunications] = useState<Communication[]>([]); const [role, setRole] = useState(''); const [loading, setLoading] = useState(true); const [draft, setDraft] = useState<{ type: 'PROVIDER' | 'PHARMACY' | 'PATIENT'; label: string } | null>(null); const [message, setMessage] = useState(''); const [forceFailure, setForceFailure] = useState(false); const [saving, setSaving] = useState(false); const [feedback, setFeedback] = useState(''); const [lastAttempt, setLastAttempt] = useState<{ type: 'PROVIDER' | 'PHARMACY' | 'PATIENT'; message: string } | null>(null);
  async function load() { setLoading(true); try { const [detailResponse, roleResponse] = await Promise.all([fetch(`/api/refills/${refillId}`), fetch('/api/demo/role')]); const detail = await detailResponse.json(); const roleBody = await roleResponse.json(); setCommunications(detail.data?.communications ?? []); setRole(roleBody.current?.role ?? ''); } catch { setFeedback('Unable to load communications.'); } finally { setLoading(false); } }
  useEffect(() => { load(); }, [refillId]);
  function openDraft(type: 'PROVIDER' | 'PHARMACY' | 'PATIENT', label: string) { setDraft({ type, label }); setMessage(`Simulated ${label.toLowerCase()} regarding refill ${refillId.slice(-8)}.`); setForceFailure(false); setFeedback(''); }
  async function send() { if (!draft || message.trim().length < 3) return; setSaving(true); setFeedback(''); setLastAttempt({ type: draft.type, message }); try { const response = await fetch(`/api/refills/${refillId}/communicate`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ type: draft.type, message, forceFailure }) }); const body = await response.json(); if (!response.ok) throw new Error(body.result?.errorMessage || body.error || 'Simulated communication failed.'); setFeedback(body.result.message); setDraft(null); await load(); await onComplete(); } catch (error) { setFeedback(error instanceof Error ? error.message : 'Simulated communication failed.'); await load(); await onComplete(); } finally { setSaving(false); } }
  const allowed = rolePermissions[role] ?? [];
  return <section className="communication-card"><div className="communication-heading"><div><span className="phase-kicker">SIMULATED OPERATIONS</span><h2>Communication center</h2></div><span className="mock-pill">MOCK / SANDBOX</span></div><p className="muted">Every message requires human confirmation and creates a communication plus audit event.</p><div className="communication-actions">{(['PROVIDER', 'PHARMACY', 'PATIENT'] as const).filter(type => allowed.includes(type)).map(type => <button className="action-button" key={type} onClick={() => openDraft(type, `Notify ${type.toLowerCase()}`)}>Notify {type.toLowerCase()} <span>→</span></button>)}</div>{feedback && <div className="communication-feedback">{feedback}</div>}{lastAttempt && feedback && <button className="retry-button" onClick={() => { setDraft({ type: lastAttempt.type, label: 'Retry notification' }); setMessage(lastAttempt.message); setForceFailure(false); }}>Retry last communication</button>}<div className="communication-list"><h3>Communication history</h3>{loading ? <div className="loading">Loading communication history...</div> : communications.length === 0 ? <div className="empty">No communications recorded yet.</div> : communications.map(item => <div className="communication-item" key={item.id}><div><strong>{item.recipient}</strong><small>{item.recipientRole} · {item.sender?.name ?? 'System'} · {new Date(item.createdAt).toLocaleString()}</small><p>{item.message}</p></div><span className={`delivery ${item.succeeded ? 'delivery-success' : 'delivery-failed'}`}>{item.succeeded ? 'Delivered · SIMULATED' : `Failed · attempt ${item.attemptCount}`}</span></div>)}</div><div className={`modal-backdrop ${draft ? 'open' : ''}`} role="presentation"><div className="phase-modal" role="dialog" aria-modal="true"><h2>Confirm simulated communication</h2><p>This will send a MOCK/SANDBOX communication to <strong>{draft?.label}</strong>. No real message will be sent.</p><textarea value={message} onChange={event => setMessage(event.target.value)} rows={4} aria-label="Communication message" /><label className="failure-toggle"><input type="checkbox" checked={forceFailure} onChange={event => setForceFailure(event.target.checked)} /> Simulate integration failure for demo</label><div className="modal-actions"><button className="secondary" onClick={() => setDraft(null)}>Cancel</button><button className="confirm" disabled={saving || message.trim().length < 3} onClick={send}>{saving ? 'Sending...' : 'Confirm simulated send'}</button></div></div></div></section>;
}
