'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import { demoFetch as fetch } from '@/lib/demo-store';

type Audit = { id: string; action: string; previousState: string | null; newState: string | null; reason: string; createdAt: string; user: { name: string } | null };
type Refill = { id: string; patient: { displayName: string; syntheticId: string }; medication: { name: string; strength: string }; pharmacy: { name: string; location: string }; provider: { name: string; specialty: string }; state: string; blocker: string | null; priority: string; nextAction: string | null; createdAt: string; tasks: { assignee: { id: string; name: string } | null }[]; auditLogs: Audit[] };
const nextStates: Record<string, { label: string; target: string }[]> = { NEW: [{ label: 'Start pharmacy review', target: 'PHARMACY_REVIEW' }], PHARMACY_REVIEW: [{ label: 'Mark blocked', target: 'BLOCKED' }], BLOCKED: [{ label: 'Route to provider', target: 'AWAITING_PROVIDER' }, { label: 'Request information', target: 'MISSING_INFORMATION' }, { label: 'Await insurance', target: 'AWAITING_INSURANCE' }, { label: 'Escalate', target: 'ESCALATED' }], MISSING_INFORMATION: [{ label: 'Start action required', target: 'ACTION_REQUIRED' }, { label: 'Escalate', target: 'ESCALATED' }], AWAITING_PROVIDER: [{ label: 'Start provider review', target: 'ACTION_REQUIRED' }, { label: 'Escalate', target: 'ESCALATED' }], AWAITING_INSURANCE: [{ label: 'Start action required', target: 'ACTION_REQUIRED' }, { label: 'Escalate', target: 'ESCALATED' }], ACTION_REQUIRED: [{ label: 'Move to in review', target: 'IN_REVIEW' }, { label: 'Escalate', target: 'ESCALATED' }], IN_REVIEW: [{ label: 'Record provider approval', target: 'APPROVAL_RECEIVED' }, { label: 'Escalate', target: 'ESCALATED' }], APPROVAL_RECEIVED: [{ label: 'Send to pharmacy', target: 'PHARMACY_PROCESSING' }], PHARMACY_PROCESSING: [{ label: 'Verify fulfillment & resolve', target: 'RESOLVED' }], ESCALATED: [{ label: 'Return to action required', target: 'ACTION_REQUIRED' }] };

function formatTime(value: string) { return new Date(value).toLocaleString([], { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' }); }
function auditTitle(event: Audit) { if (event.action === 'STATE_TRANSITION') return event.previousState ? `${event.previousState} → ${event.newState}` : `Refill received → ${event.newState}`; if (event.action === 'VERIFICATION') return 'Fulfillment verification'; if (event.action === 'COMMUNICATION') return 'Communication attempt'; if (event.action === 'ASSIGNMENT') return 'Work assignment'; if (event.action === 'ESCALATION') return 'Escalation'; return event.action; }
function roleCanTarget(role: string, target: string) { if (role === 'ADMIN') return true; if (target === 'RESOLVED') return role === 'PHARMACY_STAFF'; if (role === 'PROVIDER') return ['IN_REVIEW', 'APPROVAL_RECEIVED', 'ESCALATED'].includes(target); if (role === 'PHARMACY_STAFF') return ['PHARMACY_REVIEW', 'PHARMACY_PROCESSING'].includes(target); return target !== 'APPROVAL_RECEIVED'; }

export function RefillDetail({ id }: { id: string }) {
  const [refill, setRefill] = useState<Refill | null>(null); const [viewerId, setViewerId] = useState(''); const [viewerRole, setViewerRole] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [modal, setModal] = useState<{ label: string; target: string } | null>(null); const [reason, setReason] = useState(''); const [forceFailure, setForceFailure] = useState(false); const [saving, setSaving] = useState(false); const [assigning, setAssigning] = useState(false);
  async function load() { setLoading(true); try { const response = await fetch(`/api/refills/${id}`); const body = await response.json(); if (!response.ok) throw new Error(body.error || 'Unable to load this refill.'); setRefill(body.data); setViewerId(body.viewer.id); setViewerRole(body.viewer.role); setError(''); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to load this refill.'); } finally { setLoading(false); } }
  useEffect(() => { load(); }, [id]);
  async function confirmTransition() { if (!modal || reason.trim().length < 3) return; setSaving(true); try { const verifyingFulfillment = modal.target === 'RESOLVED'; const response = await fetch(verifyingFulfillment ? `/api/refills/${id}/verify-fulfillment` : `/api/refills/${id}/transition`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(verifyingFulfillment ? { reason, forceFailure } : { targetState: modal.target, reason }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error || 'Unable to update the refill.'); setModal(null); setReason(''); setForceFailure(false); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to update the refill.'); } finally { setSaving(false); } }
  async function assignToMe() { if (!viewerId) return; setAssigning(true); try { const response = await fetch(`/api/refills/${id}/assign`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ userId: viewerId }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error || 'Unable to assign this refill.'); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to assign this refill.'); } finally { setAssigning(false); } }
  if (loading) return <div className="loading">Loading refill details...</div>; if (error || !refill) return <div className="error-box">{error || 'Refill not found.'}</div>;
  const actions = (nextStates[refill.state] ?? []).filter(action => roleCanTarget(viewerRole, action.target));
  return <>
    <Link className="back-link" href="/refills">← Back to refill queue</Link><div className="detail-grid"><section><div className="detail-card"><div className="phase-kicker">REFILL {refill.id.slice(-8)}</div><h1 className="summary-title">{refill.patient.displayName}</h1><p className="summary-meta">Synthetic patient ID: {refill.patient.syntheticId}</p><div className="facts"><div><span className="fact-label">Current state</span><span className={`badge state state-${refill.state}`}>{refill.state}</span></div><div><span className="fact-label">Priority</span><span className={`badge priority priority-${refill.priority}`}>{refill.priority}</span></div><div><span className="fact-label">Blocker</span><span className="fact-value">{refill.blocker ?? 'None identified'}</span></div><div><span className="fact-label">Assigned user</span><span className="fact-value">{refill.tasks[0]?.assignee?.name ?? 'Unassigned'}</span></div><div><span className="fact-label">Medication</span><span className="fact-value">{refill.medication.name} {refill.medication.strength}</span></div><div><span className="fact-label">Next action</span><span className="fact-value">{refill.nextAction ?? 'Review refill context'}</span></div><div><span className="fact-label">Pharmacy</span><span className="fact-value">{refill.pharmacy.name}<br /><span className="muted">{refill.pharmacy.location}</span></span></div><div><span className="fact-label">Provider</span><span className="fact-value">{refill.provider.name}<br /><span className="muted">{refill.provider.specialty}</span></span></div></div></div><div className="detail-card timeline"><h2>Workflow timeline</h2>{refill.auditLogs.length === 0 ? <div className="empty">No timeline events yet.</div> : refill.auditLogs.map(event => <div className="timeline-item" key={event.id}><span className="timeline-time">{formatTime(event.createdAt)}</span><i className="timeline-dot" /><div className="timeline-content"><strong>{auditTitle(event)}</strong><small>{event.reason} · {event.user?.name ?? 'System'}</small></div></div>)}</div></section><aside><div className="detail-card action-panel"><h2>Action center</h2>{['ADMIN', 'PRACTICE_STAFF'].includes(viewerRole) && <button className="action-button" disabled={assigning} onClick={assignToMe}>{assigning ? 'Assigning...' : 'Assign to me'} <span>→</span></button>}{actions.length === 0 ? <p className="muted">No workflow actions are available from this state.</p> : <div className="action-list">{actions.map(action => <button className="action-button" key={action.target} onClick={() => { setReason(`${action.label} for synthetic refill.`); setForceFailure(false); setModal(action); }}>{action.label} <span>→</span></button>)}</div>}</div><div className="detail-card"><h2>Audit history</h2>{refill.auditLogs.map(event => <p key={event.id} className="muted" style={{ fontSize: 12, lineHeight: 1.5 }}><strong>{event.user?.name ?? 'System'}</strong><br />{event.reason}<br />{formatTime(event.createdAt)}</p>)}</div></aside></div>
    <div className={`modal-backdrop ${modal ? 'open' : ''}`} role="presentation"><div className="phase-modal" role="dialog" aria-modal="true"><h2>Confirm transition</h2><p>Current state: <strong>{refill.state}</strong><br />New state: <strong>{modal?.target}</strong></p><label className="fact-label" htmlFor="transition-reason">Reason</label><textarea id="transition-reason" value={reason} onChange={event => setReason(event.target.value)} rows={4} />{modal?.target === 'RESOLVED' && <label className="failure-toggle"><input type="checkbox" checked={forceFailure} onChange={event => setForceFailure(event.target.checked)} /> Simulate pharmacy verification failure for demo</label>}<div className="modal-actions"><button className="secondary" onClick={() => setModal(null)}>Cancel</button><button className="confirm" disabled={saving || reason.trim().length < 3} onClick={confirmTransition}>{saving ? 'Saving...' : 'Confirm'}</button></div></div></div>
  </>;
}
