'use client';

import { useEffect, useState } from 'react';
import { demoFetch as fetch } from '@/lib/demo-store';
import { PhaseHeader } from '@/components/phase-header';

type Metrics = { total: number; open: number; blocked: number; awaitingProvider: number; awaitingPatient: number; resolved: number; escalated: number; averageResolutionHours: number; byBlocker: Record<string, number>; byState: Record<string, number> };
function Bars({ values }: { values: Record<string, number> }) { const max = Math.max(...Object.values(values), 1); return <div className="bars">{Object.entries(values).map(([label, value]) => <div className="bar-row" key={label}><span>{label}</span><div><i style={{ width: `${Math.max(7, value / max * 100)}%` }} /></div><strong>{value}</strong></div>)}</div>; }

export default function AnalyticsPage() { const [metrics, setMetrics] = useState<Metrics | null>(null); const [error, setError] = useState(''); useEffect(() => { fetch('/api/analytics').then(async response => { const body = await response.json(); if (!response.ok) throw new Error(body.error); setMetrics(body.data); }).catch(caught => setError(caught.message)); }, []); return <div className="phase-shell"><PhaseHeader /><main className="phase-main"><div className="phase-kicker">OPERATIONS INSIGHT</div><h1 className="phase-title">Resolution analytics</h1><p className="phase-subtitle">Live metrics calculated from synthetic refill workflow data.</p>{error ? <div className="error-box">{error}</div> : !metrics ? <div className="loading">Loading operational metrics...</div> : <><section className="metric-cards"><Metric label="Total refills" value={metrics.total} /><Metric label="Open requests" value={metrics.open} /><Metric label="Blocked" value={metrics.blocked} /><Metric label="Awaiting provider" value={metrics.awaitingProvider} /><Metric label="Resolved" value={metrics.resolved} /><Metric label="Escalated" value={metrics.escalated} /><Metric label="Avg. time to resolution" value={`${metrics.averageResolutionHours} hrs`} /></section><div className="analytics-grid"><section className="detail-card"><h2>Requests by blocker</h2><Bars values={metrics.byBlocker} /></section><section className="detail-card"><h2>Requests by workflow state</h2><Bars values={metrics.byState} /></section></div></>}</main></div>; }
function Metric({ label, value }: { label: string; value: string | number }) { return <article className="metric-tile"><span>{label}</span><strong>{value}</strong></article>; }
